arb-dir: lib/core/services/l10n
template-arb-file: intl_en.arb
output-localization-file: l10n.dart
output-class: S
output-dir: lib/generated
untranslated-strings-file: intl_untranslated.json
use-escaping: false
nullable-getter: false
