// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtXzgwfL5wRLTRBKllmFAvbaJwYjoLa1s',
    appId: '1:888646898645:web:9d66fa58d4efcd8ea7e35c',
    messagingSenderId: '888646898645',
    projectId: 'ryzeai',
    authDomain: 'ryzeai.firebaseapp.com',
    storageBucket: 'ryzeai.firebasestorage.app',
    measurementId: 'G-E15H6SLRPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6JJFr9xg4nBBHLd8rvn8vp9gHWw8Z2FE',
    appId: '1:888646898645:android:1faa56b53139abf9a7e35c',
    messagingSenderId: '888646898645',
    projectId: 'ryzeai',
    storageBucket: 'ryzeai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnjU9WFpwcGaZrVhQhXBS9WINkGF_hdXo',
    appId: '1:888646898645:ios:99a74f1b2d4b8ff6a7e35c',
    messagingSenderId: '888646898645',
    projectId: 'ryzeai',
    storageBucket: 'ryzeai.firebasestorage.app',
    iosBundleId: 'com.example.ryzeai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnjU9WFpwcGaZrVhQhXBS9WINkGF_hdXo',
    appId: '1:888646898645:ios:99a74f1b2d4b8ff6a7e35c',
    messagingSenderId: '888646898645',
    projectId: 'ryzeai',
    storageBucket: 'ryzeai.firebasestorage.app',
    iosBundleId: 'com.example.ryzeai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtXzgwfL5wRLTRBKllmFAvbaJwYjoLa1s',
    appId: '1:888646898645:web:445d4385b5afdcc0a7e35c',
    messagingSenderId: '888646898645',
    projectId: 'ryzeai',
    authDomain: 'ryzeai.firebaseapp.com',
    storageBucket: 'ryzeai.firebasestorage.app',
    measurementId: 'G-3KJRCJQ9TG',
  );
}
